[tool.poetry]
name = "openai-py"
version = "0.1.0"
authors = ["koji.ono",]
description = ""
readme = "README.md"
packages = [{include = "openai_py"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "1.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
