[tool.poetry]
name = "openai-py"
version = "0.1.0"
authors = ""
description = ""
readme = "README.md"
packages = [{include = "openai_py"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
